POST http://localhost:3001/translation/keys
Content-Type: application/json

{
  "path": "/Users/marius/Developer/Github/translation_hero/testfiles/"
}

###

POST http://localhost:3001/translation/translations
Content-Type: application/json

{
  "path": "/Users/marius/Developer/Github/translation_hero/testfiles/"
}

