//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject)]
#[sea_orm(table_name = "application_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub initial_launch: bool,
    pub file_change_notification: bool,
    pub finished_scan_notification: bool,
    pub finished_translation_notification: bool,
    pub nav_open: bool,
    pub notifications_enabled: bool,
    pub resizable_panel_state: String,
    pub theme: String,
    pub toast_rich_colors: bool,
    pub translation_default_language: String,
    pub translate_new_strings: bool,
    pub translate_updated_strings: bool,
    pub translation_command: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
