// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "hi", input: never, result: string },
    mutations: 
        { key: "stores.getStore", input: string, result: Store } | 
        { key: "stores.removeStore", input: string, result: null } | 
        { key: "stores.setStore", input: Store, result: null },
    subscriptions: never
};

export type LocationStore = { state: LocationStoreState; version: number }

export type LocationStoreState = { last_selected_location?: Location | null; locations?: Location[] }

export type TranslationSettings = { translate_new_strings?: boolean; translate_updated_strings?: boolean; default_language?: string; translation_command?: string }

export type Store = SettingsStore | LocationStore | TranslationStore

export type Notifications = { file_changes?: boolean; finished_translation?: boolean; finished_scan?: boolean }

export type ResizablePanelState = { home_default_sizes?: number[]; home_nav_collapsed?: boolean; home_collapsed_size?: number }

export type SettingsStoreState = { nav_open?: boolean; theme: Theme; notifications_enabled?: boolean; toast_rich_colors?: boolean; enabled_notification_types: Notifications; translation_settings: TranslationSettings; resizable_panel_state: ResizablePanelState }

export type TranslationStoreState = { languages?: string[]; translation_entries: TranslationEntry[] }

export type Theme = "light" | "dark"

export type SettingsStore = { state: SettingsStoreState; version: number }

export type Location = { tag?: string; name?: string; path?: string; is_favourite?: boolean; num_of_keys?: number; num_of_untranslated_keys?: number; added_at?: string }

export type TranslationEntry = { key?: string; value?: string; translations?: { [key: string]: string }; in_use?: boolean }

export type TranslationStore = { state: TranslationStoreState; version: number }
