name: Checks

on: [pull_request]

jobs:
  # format_rust:

  #   runs-on: ubuntu-latest

  #    steps:
  #      - uses: actions/checkout@v2
  #      - name: Install Rust
  #        uses: actions-rs/toolchain@v1
  #        with:
  #          toolchain: '1.74.1'
  #          default: true
  #          components: rustfmt
  #      - name: Format
  #        uses: actions-rs/cargo@v1
  #        with:
  #          command: fmt
  #          args: --all -- --check
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: 1.2.2
      - name: Run Biome
        run: biome ci .
