name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for tag-based versioning

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './app-tauri -> target'
          cache-all-crates: true # Cache all dependencies for faster Windows builds

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile # Use lockfile for consistent installs

      - name: Generate prisma client
        working-directory: crates/db
        run: cargo prisma generate
        env:
          CARGO_BUILD_JOBS: 4 # Parallel compilation for faster builds

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          CARGO_BUILD_JOBS: 4 # Parallel compilation for Windows
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Hero v__VERSION__'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.platform == 'windows-latest' && '--locked --target x86_64-pc-windows-msvc' || '' }} # Optimize Windows target

      - name: Create GitHub Release
        if: matrix.platform == 'macos-latest' # Run only once to avoid duplicate releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: 'Hero v${{ github.ref_name }}'
          body: 'Automated release for Hero. See assets below for downloads.'
          draft: false
          prerelease: false
          files: |
            dist/*.dmg
            dist/*.msi
            dist/*.exe

  coverage:
    runs-on: ubuntu-latest
    needs: build-and-release # Run coverage only after successful builds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
